/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Profil de l'utilisateur courant — permet au front de restaurer la session.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Liste les comptes du tenant de l'administrateur courant.
         */
        get: operations["list_users_api_auth_users_get"];
        put?: never;
        /**
         * Create User
         * @description Crée un compte (élève ou admin) dans le tenant de l'administrateur courant.
         */
        post: operations["create_user_api_auth_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation Messages */
        get: operations["get_conversation_messages_api_conversations__conversation_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_api_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_documents_get"];
        put?: never;
        /** Upload Documents */
        post: operations["upload_documents_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Document Status Stream
         * @description SSE : émet le statut courant toutes les 500 ms jusqu'à un état terminal.
         */
        get: operations["document_status_stream_api_documents__document_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex Document */
        post: operations["reindex_document_api_documents__document_id__reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/verify-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify All Documents
         * @description Vérifie tous les documents ``indexed`` du tenant contre le vectorstore
         *     réel — détecte les documents « orphelins » (statut indexé mais chunks
         *     disparus, ex. après un changement de VECTOR_BACKEND). Les marque
         *     ``orphaned`` en conséquence ; ne les réindexe pas (le fichier original
         *     n'est pas conservé côté serveur — un ré-upload est nécessaire).
         */
        post: operations["verify_all_documents_api_documents_verify_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progression/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progression */
        get: operations["get_progression_api_progression__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Quiz
         * @description Génère un quiz sur une compétence.
         *
         *     Un quiz indisponible (``available`` faux) n'est **pas** une erreur HTTP :
         *     c'est le résultat honnête d'un modèle qui n'a rien produit d'exploitable.
         *     L'interface affiche ``instructions`` et propose de réessayer — jamais un
         *     questionnaire de remplissage.
         */
        post: operations["generate_quiz_api_quiz_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quiz/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer Quiz
         * @description Corrige une réponse, met à jour la maîtrise, attribue les badges mérités.
         */
        post: operations["answer_quiz_api_quiz_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evaluation History
         * @description Résultats d'exercices et de quiz, du plus récent au plus ancien.
         */
        get: operations["get_evaluation_history_api_evaluation__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mastery/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mastery
         * @description Niveau par compétence, compétences à retravailler, badges obtenus.
         *
         *     ``weakest`` ne contient que des compétences **réellement tentées** : une
         *     compétence jamais travaillée n'est pas « non maîtrisée », elle est inconnue,
         *     et la proposer en priorité de révision serait trompeur.
         */
        get: operations["get_mastery_api_mastery__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages/{message_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_api_messages__message_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chat Logs */
        get: operations["list_chat_logs_api_logs_chat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BadgeOut */
        BadgeOut: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
            /** Earned At */
            earned_at: string;
        };
        /** Body_reindex_document_api_documents__document_id__reindex_post */
        Body_reindex_document_api_documents__document_id__reindex_post: {
            /** File */
            file: string;
        };
        /** Body_upload_documents_api_documents_post */
        Body_upload_documents_api_documents_post: {
            /** Files */
            files: string[];
            /** Niveau */
            niveau?: string | null;
            /** Classe */
            classe?: string | null;
            /** Serie */
            serie?: string | null;
            /** Discipline */
            discipline?: string | null;
            /** Chapitre */
            chapitre?: string | null;
            /** Competence */
            competence?: string | null;
            /** Examen Associe */
            examen_associe?: string | null;
        };
        /**
         * ChatLogEntry
         * @description Un tour de chat, pour la page « Logs » (vue d'ensemble multi-élèves).
         *
         *     ``trace`` contient déjà la question (clé ``question``), le detail
         *     nœud-par-nœud (``node_trace``) et les stats de génération (``generation``)
         *     — voir ``api/routes/chat.py`` pour la construction de cet objet avant
         *     persistance.
         */
        ChatLogEntry: {
            /** Message Id */
            message_id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Student Id */
            student_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Trace */
            trace: {
                [key: string]: unknown;
            };
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /** Student Id */
            student_id?: string | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Curriculum Context */
            curriculum_context?: {
                [key: string]: string;
            };
        };
        /** ConversationOut */
        ConversationOut: {
            /** Id */
            id: string;
            /** Title */
            title: string | null;
            /** Created At */
            created_at: string;
            /** Last Message At */
            last_message_at: string;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default student
             * @enum {string}
             */
            role: "admin" | "teacher" | "parent" | "student";
            /** Student Id */
            student_id?: string | null;
            /** Display Name */
            display_name?: string | null;
        };
        /** DocumentConsistencyOut */
        DocumentConsistencyOut: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Status */
            status: string;
            /** Chunks In Store */
            chunks_in_store: number;
            /** Consistent */
            consistent: boolean;
        };
        /** DocumentOut */
        DocumentOut: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Doc Type */
            doc_type: string;
            /** Status */
            status: string;
            /** Error */
            error: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            } | null;
            /** Log */
            log?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EvaluationHistoryOut */
        EvaluationHistoryOut: {
            /** Student Id */
            student_id: string;
            /** Results */
            results: components["schemas"]["ExerciseResultOut"][];
        };
        /** ExerciseResultOut */
        ExerciseResultOut: {
            /** Id */
            id: string;
            /** Competence */
            competence?: string | null;
            /** Chapitre */
            chapitre?: string | null;
            /** Exercise Type */
            exercise_type: string;
            /** Difficulty */
            difficulty: string;
            /** Is Correct */
            is_correct?: boolean | null;
            /** Score */
            score?: number | null;
            /** Created At */
            created_at: string;
        };
        /** FeedbackOut */
        FeedbackOut: {
            /** Id */
            id: string;
            /** Message Id */
            message_id: string;
            /** Value */
            value: number;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Value
             * @enum {integer}
             */
            value: -1 | 1;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Db */
            db: boolean;
            /** Redis */
            redis: string;
            /** Qdrant */
            qdrant: string;
            /** Llm */
            llm: string[];
            /** Documents Orphaned */
            documents_orphaned: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MasteryEntryOut */
        MasteryEntryOut: {
            /** Competence */
            competence: string;
            /** Chapitre */
            chapitre?: string | null;
            /** Mastery Score */
            mastery_score: number;
            /** Attempts */
            attempts: number;
            /** Successes */
            successes: number;
            /** Statut */
            statut: string;
            /** Last Seen */
            last_seen?: string | null;
        };
        /** MasteryOut */
        MasteryOut: {
            /** Student Id */
            student_id: string;
            /** Competences */
            competences: components["schemas"]["MasteryEntryOut"][];
            /** Weakest */
            weakest: components["schemas"]["MasteryEntryOut"][];
            /** Badges */
            badges: components["schemas"]["BadgeOut"][];
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Trace */
            trace?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProgressEntryOut */
        ProgressEntryOut: {
            /** Id */
            id: string;
            /** Competence */
            competence: string | null;
            /** Hint Level */
            hint_level: number;
            /** Question */
            question: string;
            /** Created At */
            created_at: string;
        };
        /** ProgressionOut */
        ProgressionOut: {
            /** Student Id */
            student_id: string;
            /** History */
            history: components["schemas"]["ProgressEntryOut"][];
            /** Recurrent Difficulties */
            recurrent_difficulties: string[];
        };
        /** QuizAnswerRequest */
        QuizAnswerRequest: {
            /** Quiz Token */
            quiz_token: string;
            /** Answer */
            answer: string;
            /** Student Id */
            student_id?: string | null;
        };
        /** QuizChoiceOut */
        QuizChoiceOut: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** QuizCorrectionOut */
        QuizCorrectionOut: {
            /** Is Correct */
            is_correct: boolean;
            /** Correct Answer */
            correct_answer: string;
            /** Given Answer */
            given_answer: string;
            /** Explanation */
            explanation: string;
            /** Score */
            score: number;
            mastery?: components["schemas"]["MasteryEntryOut"] | null;
            /** Badges */
            badges?: components["schemas"]["BadgeOut"][];
        };
        /**
         * QuizOut
         * @description Quiz remis à l'élève. **Sans la bonne réponse** — voir ``quiz_token``.
         */
        QuizOut: {
            /** Competence */
            competence: string;
            /** Quiz Type */
            quiz_type: string;
            /** Available */
            available: boolean;
            /**
             * Question
             * @default
             */
            question: string;
            /** Choices */
            choices?: components["schemas"]["QuizChoiceOut"][];
            /**
             * Quiz Token
             * @default
             */
            quiz_token: string;
            /**
             * Instructions
             * @default
             */
            instructions: string;
        };
        /** QuizRequest */
        QuizRequest: {
            /** Competence */
            competence?: string | null;
            /**
             * Quiz Type
             * @default qcm
             * @enum {string}
             */
            quiz_type: "qcm" | "vrai_faux";
            /** Curriculum Context */
            curriculum_context?: {
                [key: string]: string;
            };
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /** Curriculum Context */
            curriculum_context?: {
                [key: string]: string;
            };
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** SearchResultOut */
        SearchResultOut: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Score */
            score: number;
            /** Dense Score */
            dense_score: number | null;
            /** Sparse Score */
            sparse_score: number | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** UploadedDocumentOut */
        UploadedDocumentOut: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Status */
            status: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Tenant Id */
            tenant_id: string;
            /** Student Id */
            student_id?: string | null;
            /** Display Name */
            display_name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyAllOut */
        VerifyAllOut: {
            /** Checked */
            checked: number;
            /** Orphaned */
            orphaned: components["schemas"]["DocumentConsistencyOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_users_api_auth_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_auth_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query?: {
                student_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_messages_api_conversations__conversation_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    upload_documents_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_documents_api_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadedDocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_status_stream_api_documents__document_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_document_api_documents__document_id__reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_reindex_document_api_documents__document_id__reindex_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadedDocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_all_documents_api_documents_verify_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyAllOut"];
                };
            };
        };
    };
    search_api_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progression_api_progression__student_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_quiz_api_quiz_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_quiz_api_quiz_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizCorrectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_history_api_evaluation__student_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationHistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mastery_api_mastery__student_id__get: {
        parameters: {
            query?: {
                weakest_limit?: number;
            };
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasteryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_messages__message_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_chat_logs_api_logs_chat_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatLogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
