"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-08 02:26:48.190775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('competence', sa.String(length=255), nullable=True),
    sa.Column('rag_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('hint_label', sa.String(length=64), nullable=False),
    sa.Column('frustration_score', sa.Float(), nullable=False),
    sa.Column('tool_used', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_index('ix_audit_log_tenant_student', 'audit_log', ['tenant_id', 'student_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_index('ix_conversations_tenant_student', 'conversations', ['tenant_id', 'student_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index('ix_documents_tenant_status', 'documents', ['tenant_id', 'status'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('competence', sa.String(length=255), nullable=True),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_tenant_id'), 'progress', ['tenant_id'], unique=False)
    op.create_index('ix_progress_tenant_student', 'progress', ['tenant_id', 'student_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('trace', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_tenant_conversation', 'messages', ['tenant_id', 'conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value IN (-1, 1)', name='ck_feedback_value'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_tenant_id'), 'feedback', ['tenant_id'], unique=False)
    op.create_index('ix_feedback_tenant_message', 'feedback', ['tenant_id', 'message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_tenant_message', table_name='feedback')
    op.drop_index(op.f('ix_feedback_tenant_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index('ix_messages_tenant_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_progress_tenant_student', table_name='progress')
    op.drop_index(op.f('ix_progress_tenant_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index('ix_documents_tenant_status', table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_conversations_tenant_student', table_name='conversations')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_audit_log_tenant_student', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
